version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www
    expose:
      - 9000

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8001:81"
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
